[IV-24-25] Objetivo 1
GaelGoncalba/AutoShopping pull request #5
Opened 2024-10-10 23:23 UTC by GaelGoncalba

Sobre los milestones
* [X] ¿Las historias de usuario y los milestones constituyen una guía
    suficiente para poder comenzar el desarrollo de un proyecto?
* [X] ¿Los milestones están ordenados correctamente, de forma que el 1 o
   0 sea lo primero que hay que empezar a publicar?
* [X] ¿Todos los milestones se construyen sobre el anterior, teniendo un
   orden lógico el desarrollo?
* [X] ¿El milestone 0 tiene asignada alguna historia de usuario?
* [X] ¿El milestone 0 corresponde con lo mencionado varias veces en
   clase, y en concreto con lo que se solicita en el objetivo
   siguiente?
* [X] ¿Todos los milestones describen correctamente un producto y qué
   lo hace válido, y no un  concepto vago, una funcionalidad o una tarea?
* [X] ¿Los milestones son graduales, o hay un salto grande entre ellos? Graduales
* [X] ¿Los milestones iniciales son internos, y hay a continuación milestones o
   productos externos?
* [X] ¿Los milestones son mínimos, es decir, incluyen un producto
   mínimamente viable para poder avanzar?
* [X] ¿El milestone 0 es mínimo *y* viable?
* [X] ¿Se indica claramente cómo comprobar la viabilidad del PMV de cada hito? Es
    decir, ¿se dice qué requisitos técnicos tiene que cumplir el producto de
    cada hito?
* [X] ¿Entre dos milestones consecutivos, no hay ningún PMV posible o por el
    contrario podrían desarrollarse muchas posibles etapas internas o externas
    de un proyecto?
Sobre las historias de usuario
* [X] ¿He tenido en cuenta en las historias de usuario que se trata de un
   proyecto que se desplegará en la nube?
* [X] ¿Están descritos todos los conceptos mencionados en las HUs con
   suficiente claridad, generalmente en documentos aparte?
   No he visto necesario aclarar aparte ningún concepto puesto que las historias de usuario que he descrito no manejan conceptos técnicos o avanzados de ningún tipo.
* [X] ¿Tienen coherencia suficiente las historias de usuario, y en caso
   de que no lo tengan, se ha escrito un *user journey* para
   aclararlo?
* [X] ¿Todas las historias de usuario representan un beneficio para el
    mismo y se relacionan con la lógica de negocio? Es decir, ¿los usuarios
    *desean* hacerlo o tú deseas que el usuario te lo pida para hacerlo?

2024-10-16 10:14 UTC, FerniCuesta commented
Buenas, se me ha asignado revisar tu PR

2024-10-16 10:29 UTC, FerniCuesta commented on README.md
> +Desarrollar una aplicación desplegada en la nube que obtenga los datos de los precios y tipos de alimento de distintos productos alimenticios **scrapeando** la información de los supermercados más co
El enfoque del README es plantear el problema, no la solución. Te sugiero que reescribas este apartado como 'Descripción del problema'. Puede tener un enfoque como el siguiente:
Soy un estudiante, por lo que tengo un presupuesto limitado a la semana para hacer la compra...cada supermercado tiene precios muy variados y no se cuál me conviene más para ir a comprar...

Algo del estilo, donde plantees el problema que más tarde vas a resolver.

2024-10-16 10:29 UTC, FerniCuesta commented on documentos/milestones.md
> +## [[M01] Fundamentos del problema](https://github.com/GaelGoncalba/AutoShopping/milestone/1)
Debes empezar la numeración de los Milestones a partir del 0 (M0, M1, ...).

2024-10-16 10:29 UTC, FerniCuesta commented on documentos/milestones.md
> +- Código funcional del núcleo de la aplicación que implemente la extracción básica de datos y la interfaz mínima con la que posteriormente interaccionará el usuario.
Tener como entregable código en el primer Milestone puede ser demasiado avanzado, intenta que el Milestone 0 sea algo más conceptual. Te sugiero que lo centres más en los conceptos clave del dominio y las relaciones entre ellos. De esta forma aporta flexibilidad a la persona que vaya a encargarse de los siguientes Milestones.

2024-10-16 18:58 UTC, GaelGoncalba commented on README.md
> +Desarrollar una aplicación desplegada en la nube que obtenga los datos de los precios y tipos de alimento de distintos productos alimenticios **scrapeando** la información de los supermercados más co
Corregido aquí: da459ef2a52d0260eabfff6f3446210b0579b1f5
Es cierto que de la manera que me has propuesto plantearlo creo que se ve mas claro el problema. Igualmente he añadido un apartado de objetivos para aclarar que es lo que se quiere hacer con el proyecto y he dejado el enlace a la web de la que se va a scrappear la información ya que no se puede extraer informacion de manera sencilla desde las webs de supermercados oficiales

2024-10-16 18:59 UTC, GaelGoncalba commented on documentos/milestones.md
> +## [[M01] Fundamentos del problema](https://github.com/GaelGoncalba/AutoShopping/milestone/1)
Corregido aquí: 029c2b07e172be2dc0842dc526e98bbafcee46a2

2024-10-16 18:59 UTC, GaelGoncalba commented on documentos/milestones.md
> +- Código funcional del núcleo de la aplicación que implemente la extracción básica de datos y la interfaz mínima con la que posteriormente interaccionará el usuario.
Corregido aquí: 0ee06112cc32d666fca21c4d72376448fcb35e3b
Ahora en el M0 sólo se pide el código que determine los elementos básicos del dominio del problema, y el código más elaborado (scrapping de la web) lo he incluido en el segundo milestone. Aunque el M1 ahora sea algo más largo que los demás es necesario que se realice el scrapping (el cual además se facilita por usar una web de terceros y no oficial de algún supermercado grande) antes de implementar la logica de generacion de listas, por lo que creo que así sería correcto.

2024-10-17 07:43 UTC, FabriConde commented
Buenas, me han asigando la revisión de tu PR.
Estoy de acuerdo con los cambios propuesto por mi compañero, ahora se entiendo mejor la descrición del problema. 
Por mi parte, lo único que puedo añadir es que se puede mejorar el M2 especificando como se va a lograr el ajuste de la lista a un presupuesto, qué tipo de algoritmo se va a usar, como se va a usar, etc.

2024-10-17 22:00 UTC, clara99gf commented
Buenas, a mí también se me ha asignado revisar tu PR.

Coincido con lo que ya han mencionado los compañeros. Además, me pregunto si el M2 no debería estar incluido en el M3, ya que el presupuesto parece ser un filtro más dentro del proceso de generación de la lista de la compra. Creo que a lo mejor se podrían simplificar ambos milestones, tratándolos como un único módulo con diferentes restricciones (como el presupuesto o tipo de productos), en lugar de separarlos en milestones distintos.

2024-10-20 10:40 UTC, GaelGoncalba commented
@clara99gf tienes razón que tanto el presupuesto como las preferencias del usuario podían formar parte del mismo módulo, los he juntado y ahora son el milestone 2. Además como añadí más funcionalidades al milestone 1 creo que así queda todo más equilibrado. @FabriConde ahora en el milestone 2 he añadido una breve descripción de cómo funciona el algoritmo pero sin detallarla demasiado para dejar algo de flexibilidad.

2024-10-21 11:29 UTC, clara99gf commented
Perfecto, te apruebo el PR!

2024-10-21 11:30 UTC, clara99gf approved these changes

2024-10-22 19:33 UTC, FabriConde approved these changes
Te apruebo la PR.

2024-10-27 10:17 UTC, GaelGoncalba commented
@JJ Solicito revision del objetivo

2024-10-28 07:14 UTC, JJ requested changes
Te rogaría que te limitaras en este objetivo a entregar el material evaluable en el mismo. Si quieres hacer algún cambio *previo*, lo puedes hacer en `main` siempre, claro está, que no introduzcas errores en lo ya aceptado y sean simplemente cambios cosméticos.

2024-10-28 07:14 UTC, JJ commented on README.md
> +Soy un estudiante con un presupuesto limitado cada semana para hacer la compra, y quiero asegurarme de que lo que gasto me permita tener una dieta lo más equilibrada posible. Sin embargo, cada superm
Si ya se aprobó en el objetivo 0 el problema, cambiarlo comporta ciertos riesgos. Toda aclaración deberías haberla hecho directamente en las historias de usuario, que es lo que se va a juzgar. Añadir cambios aquí, aparte de aportar ruido a la corrección, puede introducir incorrecciones.

2024-10-28 07:14 UTC, JJ commented on README.md
> +## Objetivos
Por ejemplo, ¿estos objetivos están solicitados en algún lugar del objetivo 0 o el 1? ¿De qué forma contribuyen a que se entienda mejor lo que se pide en el [objetivo 1](https://jj.github.io/IV/documentos/proyecto/1.Infraestructura#explicaci%C3%B3n)

2024-10-28 19:25 UTC, GaelGoncalba commented on README.md
> +## Objetivos
Estos objetivos los he añadido para que se entendiera mejor lo que quería que se hiciera en la aplicación, ya que uno de los compañeros que me ha revisado la práctica me sugirió que no pusiera de manera explícita la solución del problema en el README (la tenía especificada porque al comienzo del curso tenía otra idea de problema, y como el algoritmo para resolverlo no se entendía demasiado bien lo escribí en la descripción del problema, llamándolo "descripción de la solución". Al cambiar de problema seguí arrastrando esto, pero ahora no creo que sea necesario), y estaba de acuerdo, pero aun así quería dar algo de información acerca de la misma. No había tenido en cuenta que estos cambios no afectan en nada al objetivo 1. He vuelto a dejar el README como lo tenía en el objetivo 0, y haré los cambios directamente en el main.

2024-10-29 14:19 UTC, JJ commented on README.md
> +## Objetivos
¿Y no te parece que para entender mejor lo que sea tendrás que usar las HUs y los milestones?

2024-10-31 10:25 UTC, GaelGoncalba commented on README.md
> +## Objetivos
Sí, debería haber usado los milestones y las HU en lugar de cambiar directamente el README, pero al revisar todo el proyecto me he dado cuenta de que la información que estaba poniendo en el README era redundante, ya que esos objetivos se podían deducir de los milestones. Como he restaurado el README a como estaba antes (cuando fue aprobado el objetivo 0) creo que con la información que he añadido en las historias de usuario y los milestones ya se entiende todo.

2024-11-04 09:32 UTC, GaelGoncalba commented
@JJ con lo que tengo actualmente en las HUs y los milestones creo que ya está toda la información necesaria del problema, solicito revisión

2024-11-04 09:43 UTC, JJ requested changes
Como pone en [el fichero de errores frecuentes](https://github.com/JJ/IV-/blob/master/errores/objetivo-1.md#sobre-los-milestones):

> 

Aunque los milestones en principio no tienen por qué tener información sobre las historias de usuario, si hay varias historias de usuario hablar de "modelo del problema" o de "lógica de negocio" no es suficiente, porque las dos historias de usuario (o las 5) pueden tener diferentes aspectos del problema, o incluso ser problemas diferentes. En todo caso, siempre es conveniente ser preciso en el lenguaje, porque en el momento que se vaya a trabajar con un milestone determinado puede haber más historias de usuario, o menos, así que aclarar a qué parte del problema del cliente se circunscribe siempre es conveniente.

>    De la misma forma, enlazar todas las historias de usuario sólo indica dejadez y falta de precisión a la hora de indicar a la persona que trabaje qué es lo que debe hacer.

2024-11-04 09:43 UTC, JJ commented on documentos/milestones.md
> +### Descripción: Analizar las historias de usuario para definir los elementos del dominio del problema.
Si te has molestado en dividir el problema en historias de usuario, ¿por qué pides ahora que se analicen *todas*?

2024-11-06 09:21 UTC, GaelGoncalba commented
@JJ solicito revisión, he concretado las HUs a analizar en el milestone 0 y he especificado cada milestone con qué HU se relaciona para orientar a qué parte del problema del cliente se refiere

2024-11-06 09:42 UTC, JJ requested changes
Por favor, repasa el concepto de "producto"  y también de "mínimo" y a continuación creételo.

2024-11-06 09:42 UTC, JJ commented on documentos/milestones.md
> +### Descripción: Analizar las historias de usuario HU01 (Julián) y HU02 (Fernando) para identificar los elementos del dominio que respondan a las necesidades de presupuesto limitado y equilibrio nutr
Esto está codo como encabezado 3 porque está en la misma línea.
Por otro lado, si ya sabes que van a responder a esas necesidades y no a otras, ¿para qué quieres el análisis? Si eso está en la HU, ¿por qué lo pones? Si no está en la HU, ¿por qué no lo añades a la HU?

2024-11-06 09:42 UTC, JJ commented on documentos/milestones.md
> +- Código que abarque los elementos del dominio y las relaciones entre dichos elementos, generando clases y características propias para cada uno de ellos.
¿Qué son "características propias"? ¿Cómo vas a validar que sean "características propias"?

2024-11-06 09:42 UTC, JJ commented on documentos/milestones.md
> +- Prototipo de la aplicación con una interfaz mínima que permita mostrar los elementos del dominio del proyecto.
¿En el primer milestone ya tienes que entregar un prototipo?

2024-11-09 09:58 UTC, GaelGoncalba commented
@JJ Solicito revision

2024-11-11 09:01 UTC, JJ requested changes
Si no entendéis lo que estáis haciendo aquí y por qué es imposible que haya una combinación de palabras mágica que "acierte". Te diría que revisaras los errores frecuentes y el resto del material de la asignatura, inclusive el guión, pero al final se trata de lo mismo: tienes que entender qué es lo que se está pidiendo aquí y la importancia que tiene dentro del desarrollo de software (y la asignatura, claro)

2024-11-11 09:01 UTC, JJ commented on documentos/milestones.md
> +Analizar las historias de usuario HU01 (Julián) y HU02 (Fernando) para identificar y estructurar los elementos del dominio, incluyendo los conceptos clave y relaciones necesarias para diseñar la func
¿Los "elementos del dominio" son parte de los "fundamentos del problema" o al revés? Si a ti te dan esto, ¿sabes que tienes que hacer? ¿Sabes *tú* qué le estás pidiendo a la persona que haga esto o a ti mismo?
Por otro lado, si ya sabes que tienes que "diseñar la funcionalidad de generación de listas de compra", ¿para qué quieres hacer milestones y demás? Hazlo y listo.

2024-11-12 10:33 UTC, GaelGoncalba commented
@JJ Solicito revision. He reescrito el M0 ahora centrándolo en desarrollar el modelo inicial del problema. Así lo entiendo mejor y creo que también se entiende mejor desde fuera

2024-11-12 13:00 UTC, JJ commented
> @JJ Solicito revision. He reescrito el M0 ahora centrándolo en desarrollar el modelo inicial del problema. Así lo entiendo mejor y creo que también se entiende mejor desde fuera

¿Qué modelo inicial? ¿Va a haber un modelo final?

2024-11-13 16:45 UTC, GaelGoncalba commented
@JJ llamaba modelo inicial al modelo del problema del M0 porque determinaba los elementos fundamentales del mismo, pero al no haber un modelo final ni modelos posteriores lo he cambiado a modelo del problema, a secas. Solicito revisión.

2024-11-13 16:57 UTC, JJ commented
> @JJ llamaba modelo inicial al modelo del problema del M0 porque determinaba los elementos fundamentales del mismo, pero al no haber un modelo final ni modelos posteriores lo he cambiado a modelo del problema, a secas. Solicito revisión.

Un modelo no "determina".

2024-11-13 17:02 UTC, JJ reviewed
Conviene que tratéis de entender lo que se pide en el objetivo. Por favor, hazlo así antes de solicitar revisión de nuevo.

2024-11-13 17:02 UTC, JJ commented on documentos/milestones.md
> +Analizar las historias de usuario HU01 (Julián) y HU02 (Fernando) para desarrollar el modelo del problema.
¿Te parece que "analizar" describa una tarea o un producto? ¿Qué es lo que tiene que describirse en un milestone?

2024-11-13 17:02 UTC, JJ commented on documentos/milestones.md
> +- Código que concrete el modelo del problema, sobre el cual se desarrollará posteriormente.
¿Hay un "entregable" y un "producto"?

2024-11-13 17:02 UTC, JJ commented on documentos/milestones.md
> +- Código que define el modelo de la aplicación.
Si el entregable define el modelo "del problema", ¿por qué el producto define "el de la aplicación"?

2024-11-13 17:02 UTC, JJ commented on documentos/milestones.md
> +- El código entregado representa el modelo del problema abarcando los problemas descritos en las HU01 y HU02.
ya te dije [aquí](https://github.com/GaelGoncalba/AutoShopping/pull/5#discussion_r1827447745) algo al respecto. No voy a repetírtelo. Pero si volvemos a cometer errores que ya se han intentado corregir, va a ser muy difícil avanzar.

2024-11-13 17:02 UTC, JJ commented on documentos/milestones.md
> +### Historias de usuario asociadas:
Por favor, lee [los errores frecuentes del objetivo 1](https://github.com/JJ/IV-/blob/master/errores/objetivo-1.md).

Al menos hasta donde dice:

> En general, si se encuentra uno o más de estos "patrones suficientemente repetidos" se señalará el error, se apuntará a este fichero de errores comunes y se dejará de corregir, con lo que el estudiante tendrá que hacer otra ronda de correcciones.

2024-11-15 21:46 UTC, GaelGoncalba commented
@JJ Solicito revisión.

2024-11-18 06:46 UTC, JJ requested changes
No has resuelto todos los comentarios.

2024-11-18 06:46 UTC, JJ commented on documentos/milestones.md
> +- Código que defina el modelo del problema, sobre el cual se desarrollará posteriormente.
¿Por qué "definir" es mejor que "concretar"? ¿El modelo se "define"?

2024-11-18 23:36 UTC, GaelGoncalba commented
@JJ Solicito revisión. Cambié concretar por definir simplemente para evitar una repetición de palabras a la hora de redactar los milestones, y evitar escribir demasiadas veces la palabra 'representar', pensando que estaba poniendo sinónimos, pero es cierto que no significan lo mismo y 'representar' es lo correcto. He corregido eso y he eliminado las HU asociadas.

2024-11-19 06:30 UTC, JJ commented
> @JJ Solicito revisión. Cambié concretar por definir simplemente para evitar una repetición de palabras a la hora de redactar los milestones, y evitar escribir demasiadas veces la palabra 'representar', pensando que estaba poniendo sinónimos, pero es cierto que no significan lo mismo y 'representar' es lo correcto. He corregido eso y he eliminado las HU asociadas.

Está bien definirse objetivos concretos a la hora de describir un documento, pero "no repetir palabras" no parece que sea algo que en ingeniería del software tenga mucha importancia.

2024-11-19 06:32 UTC, JJ requested changes
Si no entendéis para qué sirve un milestone y una historia de usuario, es imposible que la describáis correctamente.
Por favor, lee de nuevo los errores comunes.

2024-11-19 06:32 UTC, JJ commented on documentos/milestones.md
> +- Código que represente el modelo del problema, sobre el cual se desarrollará posteriormente.
¿Aporta algo que tengas una "descripción" y un "entregable"?

2024-11-19 06:32 UTC, JJ commented on documentos/milestones.md
> +- El código entregado representa el modelo del problema abarcando los problemas descritos en la HU02.
¿Representa? ¿O "es"? ¿Hay un modelo del problema aparte del código que este representa?

2024-11-19 06:32 UTC, JJ commented on documentos/milestones.md
> +Desarrollo de un módulo que extraiga los datos de las fuentes seleccionadas para generar automáticamente una lista de la compra que contenga todos los alimentos necesarios para satisfacer las necesid
Si ya sabes que va a extraer los datos, ¿para qué quieres un milestone? ¿Y una historia de usuario?

2024-11-19 10:11 UTC, GaelGoncalba commented
@JJ Solicito revisión. En el M0 es verdad que la información de la descripción y del entregable era redundante, y no me había planteado prescindir de una de ellas. Respecto a si el código 'representa' o 'es' el modelo, en este caso lo 'es', y así lo he puesto ya en el milestone (he descrito que el código constituye el modelo del problema), ya que el código es todo el propio modelo del problema, no hay ningún otro modelo ni nada externo a este. También he corregido el M1, he mejorado la HU02 y ahora es más completa y se entiende mejor el problema descrito, y ahora en el propio Milestone no se detalla la solución tan concretamente y se deja más libertad a la hora de implementar las funcionalidades.

2024-11-20 09:14 UTC, JJ requested changes
Las historias de usuario tampoco parecen tener nada que ver con [el problema](https://github.com/GaelGoncalba/AutoShopping?tab=readme-ov-file#descripci%C3%B3n-del-problema) tal como lo enunciaste. Lo que yo entendí del problema, y lo que creo recordar que hablamos, trataba básicamente de extraer información de tiendas que lo publicaran en la web, centrado en los precios. Ya hablamos que sólo se podría hacer con ciertos supermercados de barrio. Soysuper.com, aparte de no ser tal cosa (y de que no sé si incluye supermercados de Granada), es un experto en scraping y me extrañaría mucho que se dejara hacer scraping.
Por favor, no cambies el enfoque del proyecto porque en ese caso no estás siguiendo lo que se aprobó.

2024-11-20 09:14 UTC, JJ commented on documentos/user-stories.md
>  Nieves es vegana, por lo que ve como un reto hacer una lista de la compra que se ajuste a sus necesidades y que no sea demasiado cara. Además tiene un hijo alérgico a determinados alimentos, por lo q
Las historias de usuario no deben mencionar una solución.

2024-11-20 09:14 UTC, JJ commented on documentos/user-stories.md
> +Fernando pasa todo el día en la oficina sentado en su despacho, llevando una vida muy sedentaria. Ha comenzado a hacer ejercicio y quiere cambiar su estilo de vida, pero le cuesta tener una dieta san
Esto también menciona una solución, y lo hacía desde el principio. Las HUs solo pueden enunciar problemas, no ningún tipo de solución. No entiendo tampoco esto nuevo qué es lo que aporta.

2024-11-20 11:56 UTC, GaelGoncalba commented
@JJ Solicito revisión. El problema trata, en parte, de extraer la informacion de productos de la web SoySuper. He elegido esa web porque tiene informacion de los supermercados más famosos y según lo que he estado investigando sí es facil de scrapear. He estado buscando información en foros y hay usuarios que han hecho proyectos con scraping de SoySuper y suelen recalcar que la página es especialmente fácil de scrapear, que no hay que hacer nada raro y muy complicado. El proyecto sigue igual, el problema es hacer una lista de la compra extrayendo los productos de esa web, y luego con un algoritmo hacer la lista y que ésta sea completa. Con la información extraída luego se podrán filtrar los productos por precio, supermercado, tipo de alimento, etc... 
He corregido también las HUs, al ir cambiándolas no había caído en que estaba describiendo las soluciones a los problemas, ya lo he redactado correctamente.

2024-11-20 17:22 UTC, JJ commented
soysuper no te va a dejar extraer información, te lo digo desde ya. Si me dices otro, puede ser.

2024-11-21 00:48 UTC, GaelGoncalba commented
@JJ otra página que me había planteado para el problema es [missupermercados](https://www.missupermercados.com/). La he estado analizando y por lo que veo no pone trabas a la hora de hacer el scrapping. He visto el robots.txt de soysuper.com y es verdad que los bots al hacer el scrapping tienen muchas restricciones, pero en el caso de missupermercados no ponen ninguna. Además la información necesaria (precio de productos, nombre, etc...) de los elementos por lo que he podido ver está estructurada fácilmente en bloques html, por lo que no creo que sea muy complicado de hacer. Creo que esta web si es adecuada para el problema.

2024-11-21 06:25 UTC, JJ commented
Gael, esto no fue lo que estuvimos hablando. Estuvimos hablando de supermercados de barrio o pequeñitos. Eso encaja más con las historias de usuario. No sé lo que pueda tener esa página, pero seguro que no tiene supermercados de un barrio de Granada. 
Y hace más de 2 meses que hablamos de esto. Podías haber buscado uno en estas fechas.

2024-11-21 09:49 UTC, GaelGoncalba commented
@JJ También había encontrado páginas de supermercados locales de granada pero pensé en hacerlo de ese tipo de webs porque cubrían varios supermercados grandes. Es verdad que se desviaba algo de la idea original. He pensado en usar la web del supermercado [SuperChisma](https://superchisma.com/). Es una cadena que tiene dos establecimientos en Granada y que la web en principio no se puede scrappear la página principal pero sí todas las páginas de categorías de productos por lo que me podría servir totalmente.

2024-11-21 10:12 UTC, JJ commented
Recuerda que para cubrir la historia de usuario tienes que poder comparar entre varios.

2024-11-21 12:09 UTC, GaelGoncalba commented
@JJ Sí, en principio también podría utilizar la web [Supermercados Sergio y David](https://www.supermercadosergioydavid.es/), ya que por lo que he podido ver no impone restricciones en la recolección automática de datos y hay un establecimiento en Granada. De esa manera ya tendría más de un supermercado disponible y podría cubrir el problema descrito en la HU y comparar entre los supermercados o filtrar si no quieres productos de uno u otro.

2024-11-21 12:29 UTC, GaelGoncalba commented
@JJ Sí, en principio también podría utilizar la web [Supermercados El Jamon](https://www.supermercadoseljamon.com/), que es una cadena de supermercados que tiene dos establecimientos en Granada y según lo que he podido analizar permite el scrapping necesario para obtener la información de los productos. Con esa web ya serían más de una las disponibles para resolver el problema y ya se podría cubrir el problema descrito en la HU, y comparar supermercados además de poder filtrar si quieres o no productos de un determinado supermercado. Si fuesen necesarias más tiendas podría plantearme scrappear [Supermercados Sergio y David](https://www.supermercadosergioydavid.es/), que también tiene un local en Granada, pero esta web requiere rellenar un formulario para poner tu edad al entrar, complicando el scrapping, podría automatizarlo pero no hay disponible ni términos de uso ni políticas de privacidad para comprobar si puedo hacerlo o no, por lo que creo que con SuperChisma y Supermercados El Jamón ya podría llevar a cabo el problema.

2024-11-21 13:19 UTC, JJ commented
Añádelo a la hU o al UJ que corresponda a esa hU, por favor.

2024-11-21 13:28 UTC, jacarmona364 reviewed
Buenas, se me ha asignado revisar tu PR. Te iré dejando algunas recomendaciones, puedes darle una vuelta a lo siguiente:

2024-11-21 13:28 UTC, jacarmona364 commented on documentos/milestones.md
> +- Módulo funcional que implemente criterios nutricionales que aseguren que las listas generadas son equilibradas y completas.
Revisa en los [errores frecuentes](https://github.com/JJ/IV-/blob/master/errores/objetivo-1.md) acerca de la importancia de la estructura que le estás dando a tus milestones, sobre las diferencias entre "descripción" y "entregable".

2024-11-21 15:10 UTC, GaelGoncalba commented on documentos/milestones.md
> +- Módulo funcional que implemente criterios nutricionales que aseguren que las listas generadas son equilibradas y completas.
Es verdad que las descripciones que estaba poniendo a cada milestone eran en su mayoría redundantes, no tiene sentido tener dos apartados distintos cuya información es tan similar. Ya me había pasado en el M0. He completado los apartados de entregables de M1 y M2 para que tengan toda la información y he prescindido de las descripciones. Corregido aquí: 7e6757baf4b8b61208bba00a429238c221bb1b95

2024-11-21 15:38 UTC, GaelGoncalba commented
@JJ Ya he añadido las webs para extraer los datos en el UJ correspondiente a la HU. Ahora la que antes era HU02 es la HU01 y viceversa, lo he modificado en todos los archivos necesarios, es sólo para que sea más intuitivo.

2024-11-21 18:27 UTC, JJ commented
Por lo pronto, espero que @jacarmona364 apruebe o te solicite algún otro cambio, si no te importa.

2024-11-22 07:48 UTC, jacarmona364 commented on documentos/milestones.md
> +- Módulo funcional que implemente criterios nutricionales que aseguren que las listas generadas son equilibradas y completas.
Quizá la manera óptima para llegar al PMV no pase por describir las partes de la aplicación, si es necesario volver a dividir el problema puede que algo falle. Ten en cuenta que un milestone no debe mostrarse como una serie de tareas, sino como un punto clave del proyecto al que se debe llegar.

2024-11-22 07:53 UTC, jacarmona364 commented on documentos/milestones.md
> +## [[M2] Ajuste y filtrado de la lista de la compra a un presupuesto y preferencias](https://github.com/GaelGoncalba/AutoShopping/milestone/3)
En desarrollo ágil no tiene mucho sentido planificar más de 2 milestone por delante y, en caso de ser necesario, deberías adaptarlo para los próximos objetivos.

2024-11-22 07:54 UTC, jacarmona364 commented
Recuerda también ir resolviendo los comentarios conforme se realicen los cambios.

2024-11-22 15:25 UTC, GaelGoncalba commented on documentos/milestones.md
> +- Módulo funcional que implemente criterios nutricionales que aseguren que las listas generadas son equilibradas y completas.
He descrito el entregable de nuevo evitando dividirlo en una serie de subtareas. Ahora es una meta clara que se debe alcanzar en el desarrollo del proyecto. Corregido aquí: 5e9bb7bbc5f2b8cad358494f6e77b890cb25e343

2024-11-22 15:28 UTC, GaelGoncalba commented on documentos/milestones.md
> +## [[M2] Ajuste y filtrado de la lista de la compra a un presupuesto y preferencias](https://github.com/GaelGoncalba/AutoShopping/milestone/3)
Finalmente he decidido planificar dos milestones en lugar de tres, ya que el M2 y el M1 podrían englobarse en un mismo milestone porque tratan funcionalidades muy interrelacionadas, de hecho así creo que es mejor a la hora de desarrollar la solución. Corregido aquí: a1f3bbd3a17ac04aae8914ad2a7fb78ad1c0ab24

2024-11-26 11:10 UTC, jacarmona364 reviewed
Aquí dejo algunas aportaciones sobre los nuevos cambios. Mucho ánimo.

2024-11-26 11:10 UTC, jacarmona364 commented on documentos/milestones.md
> +- Código que resuelva el problema planteado en la HU02 (Julián) y en la HU03 (Nieves) implementando una funcionalidad que, a partir de un conjunto de datos de productos, genere listas de la compra se
Recuerda que un milestone no debe representarse como una tarea o una lista de "cosas que hacer" para alcanzar la solución, si no como un punto clave del proyecto al que debes llegar. Trata de enfocarte en lo que se pide en el hito más que en la forma de hacerlo pues, si no, estás hablando de la solución del problema.

2024-11-26 11:10 UTC, jacarmona364 commented on documentos/milestones.md
> +- Las listas generadas respetan completamente el presupuesto máximo ingresado y las preferencias del usuario.
Debes considerar que lo que entiendes como producto viable resuelva el problema descrito en la historia de usuario. Si en esa historia de usuario ya se describe el problema, ¿por qué explicar también la solución del mismo en el milestone?

2024-11-26 11:10 UTC, jacarmona364 commented on documentos/user-stories.md
> +## [[HU01] Fernando, oficinista](https://github.com/GaelGoncalba/AutoShopping/issues/3)
Si tu problema va más encaminado a abaratar los costes de la compra, ¿no deberías darle más importancia a la HU2? En cualquier caso, si añades más historias, deben estar relacionadas con tu problema inicial.

2024-11-26 12:34 UTC, GaelGoncalba commented on documentos/milestones.md
> +- Código que resuelva el problema planteado en la HU02 (Julián) y en la HU03 (Nieves) implementando una funcionalidad que, a partir de un conjunto de datos de productos, genere listas de la compra se
Corregido aquí: aa40849834855c988ddc4e256baefb5fed3ace57
Es verdad que estaba describiendo la solución del problema sin darme cuenta. Ahora sólo indico el objetivo al que llegar, en lugar de cómo hacerlo

2024-11-26 12:35 UTC, GaelGoncalba commented on documentos/milestones.md
> +- Las listas generadas respetan completamente el presupuesto máximo ingresado y las preferencias del usuario.
Corregido aquí: aa40849834855c988ddc4e256baefb5fed3ace57
He cambiado la viabilidad del milestone ya que en las HU ya se describía correctamente el problema. Ya no está explicado de nuevo en el milestone.

2024-11-26 12:48 UTC, GaelGoncalba commented on documentos/user-stories.md
> +## [[HU01] Fernando, oficinista](https://github.com/GaelGoncalba/AutoShopping/issues/3)
Corregido aquí: 762e250382faa74bf364310742c5b6db4094d419
Mi problema está mas centrado en poder hacer listas de la compra equilibradas de manera rápida, sin pasar mucho tiempo haciéndolas. Luego, como un añadido, esas listas se podrían adaptar a un presupuesto o ser personalizadas. Sin embargo ese objetivo no se veía de manera clara en mis HUs, por lo que las he redactado de manera que ahora se vea todo más claro.

2024-11-26 17:30 UTC, jacarmona364 commented on documentos/milestones.md
> +- Código que implemente el módulo de generación automática de listas de la compra semanales a partir de un conjunto de datos de productos, atendiendo a los problemas y necesidades descritos en la HU0
Por poner alguna pega, ojo con el lenguaje, ¿el código implementa el módulo, o hablamos de un módulo de código implementado?

2024-11-26 20:06 UTC, GaelGoncalba commented on documentos/milestones.md
> +- Código que implemente el módulo de generación automática de listas de la compra semanales a partir de un conjunto de datos de productos, atendiendo a los problemas y necesidades descritos en la HU0
Corregido aquí: dd3a91e089d939671d9032cec7637b84f6a4dee8
Tienes razón, me refería a un módulo de código implementado, al redactarlo yo lo entendía pero podía llegar a ser confuso.

2024-11-28 11:44 UTC, jacarmona364 commented on documentos/milestones.md
> +- El código entregado representa el modelo del problema abarcando los problemas descritos en la HU01.
Si la HU1 abarca problemas, no se ha definido bien. ¿Quieres decir que representa el modelo descrito en la HU1? También recuerdo un comentario del profesor donde preguntaba si el código "representa" o "es" el modelo del problema. Estás muy cerca del aprobado pero debes pulir este tipo de minucias en el lenguaje para trabajar en los siguientes objetivos.

2024-11-28 12:38 UTC, jacarmona364 commented on documentos/milestones.md
> +- Módulo de código implementado que permite la generación automática de listas de la compra semanales a partir de un conjunto de datos de productos, atendiendo a los problemas y necesidades descritos
Si en el M0 se va a trabajar sobre la HU1, ¿tiene sentido trabajar sobre las otras 2? Ten en cuenta que no deben hablar las 3 historias del mismo problema, pues no aportaría nada con respecto a dejar solo la primera.

2024-11-28 17:09 UTC, GaelGoncalba commented on documentos/milestones.md
> +- El código entregado representa el modelo del problema abarcando los problemas descritos en la HU01.
Corregido aquí: 354f261ff8320b8d3869ae0e8f966c788256014e
Quería decir que representa el modelo descrito en la HU1, ya lo he corregido para que esté bien redactado y se entienda mejor. Además he aclarado que el código 'es' o constituye el modelo del problema, ya que no lo aclaré en ese apartado.

2024-11-28 17:13 UTC, GaelGoncalba commented on documentos/milestones.md
> +- Módulo de código implementado que permite la generación automática de listas de la compra semanales a partir de un conjunto de datos de productos, atendiendo a los problemas y necesidades descritos
Corregido aquí: 354f261ff8320b8d3869ae0e8f966c788256014e
Y aquí: 509ba6ed3426199cc4b5c52c480fda23e33857ba
Esto lo estuve considerando (porque mis 3 HUs hablaban de problemas muy correlacionados entre sí), pero nunca me había planteado dejar sólo una HU, sin embargo creo que es lo más adecuado. Ahora sólo tengo una HU en la que se describe el problema en su totalidad, ya que lo que antes consideraba 3 problemas se pueden presentar como 1 sólo, y está mejor organizado.

2024-12-01 17:58 UTC, jacarmona364 reviewed
He hecho algunas correcciones sobre los últimos cambios propuestos:

2024-12-01 17:58 UTC, jacarmona364 commented on documentos/milestones.md
> +- Módulo de código implementado que permite la generación automática de listas de la compra semanales a partir de un conjunto de datos de productos, atendiendo a los problemas y necesidades descritos
Con los cambios introducidos en las HUs y teniendo en cuenta el concepto de milestone, ¿dirías que hablar de generar una lista de la compra semanal es correcto? Recuerda que no debes hablar de la solución del problema, si no tratar qué se quiere obtener sobre el M0 ya alcanzado en base al problema de la HU1, sin saber si la solución sería esa u otra.

2024-12-01 17:58 UTC, jacarmona364 commented on documentos/user-stories.md
> +Fernando pasa muchas horas del día sentado delante del ordenador, llevando una vida muy sedentaria. Quiere llevar una vida más saludable y equilibrada, pero no tiene tiempo para planificar su dieta s
¿Dirías que si tienes que poner "además" o "por último" se ha dividido correctamente el problema? No digo que esté mal, pero si estamos tratando el mismo problema no debe parecer que son varios.

2024-12-02 12:18 UTC, GaelGoncalba commented on documentos/milestones.md
> +- Módulo de código implementado que permite la generación automática de listas de la compra semanales a partir de un conjunto de datos de productos, atendiendo a los problemas y necesidades descritos
Corregido aquí: d937fc978391f19015df1d77f95315bb05503bd0
Ahora en el M1 no se habla de la posible solución del problema, sólo se dice lo que se quiere obtener sin describir una solución concreta

2024-12-02 12:23 UTC, GaelGoncalba commented on documentos/user-stories.md
> +Fernando pasa muchas horas del día sentado delante del ordenador, llevando una vida muy sedentaria. Quiere llevar una vida más saludable y equilibrada, pero no tiene tiempo para planificar su dieta s
Corregido aquí: ff0f4a8d607c4cdfd7b499b72d627faef74fe6a4
Ahora la HU01 está redactada de manera que todo forma parte de un mismo problema

2024-12-03 07:43 UTC, jacarmona364 approved these changes
Considero que ya no hay ninguna incongruencia, tienes mi aprobado. 👍

2024-12-03 09:37 UTC, GaelGoncalba commented
@JJ Solicito revisión

2024-12-03 12:45 UTC, JJ reviewed
:+1:  Y muchas gracias a @jacarmona364 por su ayuda.

2024-12-03 12:45 UTC, JJ commented on documentos/milestones.md
> +- Módulo de código implementado que, utilizando el modelo creado en el M0, resuelva el problema descrito en la HU01.
¿Qué es "código implementado"? ¿En qué se diferencia de "código"?

2024-12-04 18:47 UTC, GaelGoncalba commented on documentos/milestones.md
> +- Módulo de código implementado que, utilizando el modelo creado en el M0, resuelva el problema descrito en la HU01.
No me había dado cuenta de que lo había redactado así, quería decir simplemente código. Ya lo he corregido en: db5ef32a884659592a92fb904eaa765336c0d94e

2024-12-04 23:47 UTC, merged